[package]
name = "morsecode_encoder_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "0.3"
snailquote = "0.1.1"
regex = "1"
colored = "2.0.0"